global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8081"]
    metrics_path: /metrics

  - job_name: "product-service"
    static_configs:
      - targets: ["product-service:8082"]
    metrics_path: /metrics

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8083"]
    metrics_path: /metrics

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8084"]
    metrics_path: /metrics

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8085"]
    metrics_path: /metrics

  - job_name: "search-service"
    static_configs:
      - targets: ["search-service:8086"]
    metrics_path: /metrics

  - job_name: "keycloak"
    static_configs:
      - targets: ["keycloak:8180"]
    metrics_path: /metrics
